import type { Metadata } from "next";
import "@/app/globals.css";
import { Navbar } from "@/components/globals/navbar";
import { cormorant, openSans } from "@/utils/font";

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
} ) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${cormorant.variable}  ${openSans.variable} font-openSans`}
        >
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
